// <auto-generated />
using System;
using Cognition.Domains.Relational;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cognition.Domains.Relational.Migrations
{
    [DbContext(typeof(CognitionDomainsDbContext))]
    [Migration("20260101063715_InitialDomains")]
    partial class InitialDomains
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cognition.Domains.Assets.KnowledgeAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("asset_type");

                    b.Property<Guid?>("BoundedContextId")
                        .HasColumnType("uuid")
                        .HasColumnName("bounded_context_id");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("content_hash");

                    b.Property<string>("ContentRef")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("content_ref");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("DerivedFromAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("derived_from_asset_id");

                    b.Property<Guid>("DomainId")
                        .HasColumnType("uuid")
                        .HasColumnName("domain_id");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("ScopeString")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("scope_string");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_knowledge_assets");

                    b.HasIndex("ScopeString")
                        .HasDatabaseName("ix_knowledge_assets_scope_string");

                    b.HasIndex("DomainId", "ContentHash")
                        .HasDatabaseName("ix_knowledge_assets_domain_hash");

                    b.ToTable("knowledge_assets", (string)null);
                });

            modelBuilder.Entity("Cognition.Domains.Domains.BoundedContext", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContextKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("context_key");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("DomainId")
                        .HasColumnType("uuid")
                        .HasColumnName("domain_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_bounded_contexts");

                    b.HasIndex("DomainId")
                        .HasDatabaseName("ix_bounded_contexts_domain_id");

                    b.HasIndex("DomainId", "ContextKey")
                        .IsUnique()
                        .HasDatabaseName("ux_bounded_contexts_domain_context_key");

                    b.ToTable("bounded_contexts", (string)null);
                });

            modelBuilder.Entity("Cognition.Domains.Domains.Domain", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CanonicalKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("canonical_key");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("CurrentManifestId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_manifest_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentDomainId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_domain_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_domains");

                    b.HasIndex("CanonicalKey")
                        .IsUnique()
                        .HasDatabaseName("ux_domains_canonical_key");

                    b.HasIndex("CurrentManifestId");

                    b.HasIndex("ParentDomainId")
                        .HasDatabaseName("ix_domains_parent_domain_id");

                    b.ToTable("domains", (string)null);
                });

            modelBuilder.Entity("Cognition.Domains.Domains.DomainManifest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AllowedEmbeddingFlavors")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("allowed_embedding_flavors");

                    b.Property<string>("AllowedToolCategories")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("allowed_tool_categories");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DefaultEmbeddingFlavor")
                        .HasColumnType("text")
                        .HasColumnName("default_embedding_flavor");

                    b.Property<Guid>("DomainId")
                        .HasColumnType("uuid")
                        .HasColumnName("domain_id");

                    b.Property<string>("IndexIsolationPolicy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("index_isolation_policy");

                    b.Property<DateTime?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at_utc");

                    b.Property<string>("RequiredMetadataSchema")
                        .HasColumnType("jsonb")
                        .HasColumnName("required_metadata_schema");

                    b.Property<string>("SafetyProfile")
                        .HasColumnType("text")
                        .HasColumnName("safety_profile");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_domain_manifests");

                    b.HasIndex("DomainId")
                        .HasDatabaseName("ix_domain_manifests_domain_id");

                    b.HasIndex("DomainId", "Version")
                        .IsUnique()
                        .HasDatabaseName("ux_domain_manifests_domain_version");

                    b.ToTable("domain_manifests", (string)null);
                });

            modelBuilder.Entity("Cognition.Domains.Events.EventType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid?>("DomainId")
                        .HasColumnType("uuid")
                        .HasColumnName("domain_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("SchemaJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("schema_json");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_event_types");

                    b.HasIndex("DomainId")
                        .HasDatabaseName("ix_event_types_domain_id");

                    b.HasIndex("DomainId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_event_types_domain_name");

                    b.ToTable("event_types", (string)null);
                });

            modelBuilder.Entity("Cognition.Domains.Policies.Policy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AppliesToScope")
                        .HasColumnType("text")
                        .HasColumnName("applies_to_scope");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("DenyByDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("deny_by_default");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("DomainId")
                        .HasColumnType("uuid")
                        .HasColumnName("domain_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("RulesJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("rules_json");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_policies");

                    b.HasIndex("DomainId")
                        .HasDatabaseName("ix_policies_domain_id");

                    b.HasIndex("DomainId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_policies_domain_name");

                    b.ToTable("policies", (string)null);
                });

            modelBuilder.Entity("Cognition.Domains.Scopes.ScopeInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("BoundedContextId")
                        .HasColumnType("uuid")
                        .HasColumnName("bounded_context_id");

                    b.Property<string>("CompiledScopeString")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("compiled_scope_string");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DimensionValues")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("dimension_values");

                    b.Property<Guid?>("DomainId")
                        .HasColumnType("uuid")
                        .HasColumnName("domain_id");

                    b.Property<Guid>("ScopeTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("scope_type_id");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_scope_instances");

                    b.HasIndex("BoundedContextId")
                        .HasDatabaseName("ix_scope_instances_context_id");

                    b.HasIndex("DomainId")
                        .HasDatabaseName("ix_scope_instances_domain_id");

                    b.HasIndex("ScopeTypeId", "CompiledScopeString")
                        .IsUnique()
                        .HasDatabaseName("ux_scope_instances_type_compiled");

                    b.ToTable("scope_instances", (string)null);
                });

            modelBuilder.Entity("Cognition.Domains.Scopes.ScopeType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CanonicalizationRules")
                        .HasColumnType("jsonb")
                        .HasColumnName("canonicalization_rules");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("FormatPattern")
                        .HasColumnType("text")
                        .HasColumnName("format_pattern");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("OrderedDimensions")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("ordered_dimensions");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_scope_types");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ux_scope_types_name");

                    b.ToTable("scope_types", (string)null);
                });

            modelBuilder.Entity("Cognition.Domains.Tools.ToolDescriptor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AuditTags")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("audit_tags");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("HumanGateRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("human_gate_required");

                    b.Property<string>("InputSchema")
                        .HasColumnType("jsonb")
                        .HasColumnName("input_schema");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("OutputSchema")
                        .HasColumnType("jsonb")
                        .HasColumnName("output_schema");

                    b.Property<Guid>("OwningDomainId")
                        .HasColumnType("uuid")
                        .HasColumnName("owning_domain_id");

                    b.Property<string>("RequiredApprovals")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("required_approvals");

                    b.Property<string>("SideEffectProfile")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("side_effect_profile");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_tool_descriptors");

                    b.HasIndex("OwningDomainId")
                        .HasDatabaseName("ix_tool_descriptors_domain_id");

                    b.HasIndex("OwningDomainId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_tool_descriptors_domain_name");

                    b.ToTable("tool_descriptors", (string)null);
                });

            modelBuilder.Entity("Cognition.Domains.Domains.BoundedContext", b =>
                {
                    b.HasOne("Cognition.Domains.Domains.Domain", null)
                        .WithMany("BoundedContexts")
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bounded_contexts_domain");
                });

            modelBuilder.Entity("Cognition.Domains.Domains.Domain", b =>
                {
                    b.HasOne("Cognition.Domains.Domains.DomainManifest", null)
                        .WithMany()
                        .HasForeignKey("CurrentManifestId")
                        .HasConstraintName("fk_domains_current_manifest");
                });

            modelBuilder.Entity("Cognition.Domains.Domains.DomainManifest", b =>
                {
                    b.HasOne("Cognition.Domains.Domains.Domain", null)
                        .WithMany("ManifestHistory")
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_domain_manifests_domain");
                });

            modelBuilder.Entity("Cognition.Domains.Policies.Policy", b =>
                {
                    b.HasOne("Cognition.Domains.Domains.Domain", null)
                        .WithMany("Policies")
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_policies_domain");
                });

            modelBuilder.Entity("Cognition.Domains.Domains.Domain", b =>
                {
                    b.Navigation("BoundedContexts");

                    b.Navigation("ManifestHistory");

                    b.Navigation("Policies");
                });
#pragma warning restore 612, 618
        }
    }
}
