// <auto-generated />
using Cognition.Data.Relational;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Cognition.Data.Relational.Migrations
{
    [DbContext(typeof(CognitionDbContext))]
    [Migration("20251005102500_RemoveLegacyFictionTools")]
    partial class RemoveLegacyFictionTools
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            SnapshotInvoker.Invoke(modelBuilder);
        }

        private sealed class SnapshotInvoker : CognitionDbContextModelSnapshot
        {
            public static void Invoke(ModelBuilder modelBuilder)
            {
                var snapshot = new SnapshotInvoker();
                snapshot.BuildSnapshot(modelBuilder);
            }

            private void BuildSnapshot(ModelBuilder modelBuilder)
            {
                base.BuildModel(modelBuilder);
            }
        }
    }
}
